#!/usr/bin/env bash
# new-project.sh — Bootstrap a new project directory under agent-knowledge.
#
# Usage:
#   bash new-project.sh <project-name>
#
# Example:
#   bash new-project.sh chip1-mobile
#
# This creates:
#   ~/agent-knowledge/<project-name>/
#   ├── MEMORY.md   (template with placeholder)
#   ├── SKILL.md    (template with before-starting-work instructions)
#   ├── update-memory.sh  (symlink to chip1/update-memory.sh)
#   ├── memory-search     (symlink to chip1/memory-search)
#   ├── memory_lib.py     (symlink to chip1/memory_lib.py)
#   └── pr-memory.sh      (symlink to chip1/pr-memory.sh)
#
# Symlinks keep the tooling in sync across all projects — update one, update all.

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: bash new-project.sh <project-name>"
  echo ""
  echo "Creates a new project directory under agent-knowledge/ with shared tooling."
  exit 1
fi

PROJECT="$1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET_DIR="$ROOT_DIR/$PROJECT"

if [ -d "$TARGET_DIR" ]; then
  echo "ERROR: Project '$PROJECT' already exists at $TARGET_DIR"
  exit 1
fi

# ── Create directory ────────────────────────────────────────────────────

mkdir -p "$TARGET_DIR"

# ── Symlink shared scripts ──────────────────────────────────────────────

ln -s "../chip1/update-memory.sh" "$TARGET_DIR/update-memory.sh"
ln -s "../chip1/memory-search" "$TARGET_DIR/memory-search"
ln -s "../chip1/memory_lib.py" "$TARGET_DIR/memory_lib.py"
ln -s "../chip1/pr-memory.sh" "$TARGET_DIR/pr-memory.sh"
echo "  symlinks created"

# ── Create SKILL.md ─────────────────────────────────────────────────────

cat > "$TARGET_DIR/SKILL.md" << 'SKILLEOF'
---
name: PROJECT_NAME-memory
description: Shared project memory for PROJECT_NAME. Read MEMORY.md before starting work; call update-memory.sh when discovering new conventions.
---

# Memory Journal — PROJECT_NAME

This project uses the shared agent-knowledge system.

## Before Starting Work

Search this project's memory journal, and optionally include patterns from sibling projects:

```bash
# Sync shared knowledge
(cd ~/agent-knowledge && git pull --rebase)

# Search this project
~/agent-knowledge/PROJECT_NAME/memory-search "<describe your task>"

# Also search sibling projects for cross-project patterns
~/agent-knowledge/PROJECT_NAME/memory-search --include chip1 "<describe your task>"
```

Then read the top matching entries from MEMORY.md.

## When Discovering a New Convention

```bash
echo '{
  "action":"add",
  "title":"Title of the decision",
  "context":"Why this decision was made",
  "pattern":"The actionable convention or rule",
  "tags":"tag1, tag2, tag3",
  "author":"your-name",
  "sourceFiles":["path/to/file.tsx"],
  "relatedDocs":["path/to/doc.md"]
}' | bash ~/agent-knowledge/PROJECT_NAME/update-memory.sh --push
```

## MEMORY.md Format

Entries are stored as markdown tables. Use update-memory.sh for CRUD — never edit manually.
SKILLEOF

sed -i "s/PROJECT_NAME/$PROJECT/g" "$TARGET_DIR/SKILL.md"

# ── Create MEMORY.md ────────────────────────────────────────────────────

DATE=$(date +%Y-%m-%d)

cat > "$TARGET_DIR/MEMORY.md" << MEMEOF
# Project Memory Journal — $PROJECT

This file is the chronological, write-time-intelligence journal of conventions, decisions, and discoveries for the $PROJECT project.

Managed by \`$PROJECT/update-memory.sh\`.

**Do not edit this file manually** — use \`update-memory.sh\` to ensure CRUD logic is applied.

---

## Memory Index

Searchable categories. Each entry also has \`<sup>Tags: ...</sup>\` for finer-grained search.

*No entries yet. Add the first one with \`update-memory.sh\`.*

---

## Active Decisions

| Date | Title | Author | Details |
|------|-------|--------|---------|
| $DATE | **Initial project setup** | system | **Context:** Bootstrap of $PROJECT memory journal.<br>**Pattern:** Search recursively — run \`memory-search --include chip1 "<query>"\` to inherit cross-project patterns from established projects.<br><sup>Tags: bootstrap, cross-project, setup</sup> |

---

## Archived Decisions

*No archived entries.*
MEMEOF

# ── Done ────────────────────────────────────────────────────────────────

echo ""
echo "  Created project '$PROJECT' at $TARGET_DIR"
echo ""
echo "  Next steps:"
echo "    1. cd ~/agent-knowledge && git add $PROJECT && git commit -m \"$PROJECT: bootstrap\" && git push"
echo "    2. Add CLAUDE.md triggers pointing at ~/agent-knowledge/$PROJECT/"
echo "    3. Search with cross-project inheritance:"
echo "       python3 ~/agent-knowledge/$PROJECT/memory-search --include chip1 \"<query>\""
echo ""
